### ISSUE TITLE
Spectrum Analyzer Doesn't Work When The Window's Height Is Bigger Than The Width.

### ISSUE THREAD

**Issue by alixsep** [edwardball/academo.org#12]
Hey,
when I was having my browser take half my screen size it didn't work. As soon as I resized the window to normal it worked.

![image](https://user-images.githubusercontent.com/59757582/169154813-62ab47ba-0436-4641-9b18-3a0eb295aa4b.png)

**Comment by edwardball** [comment]
Hi @alixsep thank you for raising this issue - you're right, there was a bug that was stopping the display from functioning properly on certain screen sizes. I've spent some time looking into it, and I believe the issue should now be resolved.

Thanks,
Ed
